name: pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        cache: 'pip'
    - run: pip install -r requirements.txt
    - run: bikeshed update
    - run: make
    - uses: actions/upload-pages-artifact@v3
    - id: deployment
      uses: actions/deploy-pages@v4
